version: '3.8'

services:
  app:
    build: .
    container_name: node_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      DOCKER_ENV: "true"
      MONGO_URI: "mongodb+srv://finikhil2432:pFXkCy6CVQYM82t1@cluster0.l44y4.mongodb.net/retail_pulse?retryWrites=true&w=majority"
      REDIS_URL: "redis://redis:6379"

  worker:
    build: .
    container_name: worker_service
    restart: always
    depends_on:
      - redis
    command: ["node", "worker/worker.js"] # ✅ This will start the worker automatically
    environment:
      DOCKER_ENV: "true"
      MONGO_URI: "mongodb+srv://finikhil2432:pFXkCy6CVQYM82t1@cluster0.l44y4.mongodb.net/retail_pulse?retryWrites=true&w=majority"
      REDIS_URL: "redis://redis:6379"

  redis:
    image: redis:latest
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
